# -*- restclient -*-
#
# This is Emacs restclient file meant for ad hoc testing.
# See https://github.com/pashky/restclient.el for details.

# see https://github.com/pashky/restclient.el/issues/149
:token := my-restclient-token
:comment-id := my-restclient-comment-id

## Users

# Register user "tester". He will follow "stallman"
POST http://localhost:8000/api/users
Content-Type: application/json

{"user": {"username": "tester", "email": "tester@realworld.io", "password": "rust is awesome"}}

# Register user "stallman". He will write snacks
POST http://localhost:8000/api/users
Content-Type: application/json

{"user": {"username": "stallman", "email": "stallman@gnu.org", "password": "free software"}}

# Login as "tester"
POST http://localhost:8000/api/users/login
Content-Type: application/json

{"user": {"email": "tester@realworld.io", "password": "rust is awesome"}}

# Login as "stallman"
POST http://localhost:8000/api/users/login
Content-Type: application/json

{"user": {"email": "stallman@gnu.org", "password": "free software"}}

# Get user data. Requires token, so either register or login first.
GET http://localhost:8000/api/user
Authorization: Token :token

# Update user bio
PUT http://localhost:8000/api/user
Content-Type: application/json
Authorization: Token :token

{"user": {"bio": "I made FSF"}}

## snacks

# Create new snack.
#
# Other snack related rest need a slug, so consider disabled
# randomized slug suffixes: `cargo run --no-default-features`
POST http://localhost:8000/api/snacks
Content-Type: application/json
Authorization: Token :token

{
    "snack": {
        "title": "Test snack",
        "description": "Just some tests",
        "body": "Lorem ipsum",
        "tagList": [
            "foo",
            "bar"
        ]
    }
}

# Get snack anonymously
GET http://localhost:8000/api/snacks/test-snack

# Get snack as current user
GET http://localhost:8000/api/snacks/test-snack
Authorization: Token :token

# Update snack description and overwrite tags
PUT http://localhost:8000/api/snacks/test-snack
Content-Type: application/json
Authorization: Token :token

{"snack": {"description": "New description", "tagList": ["baz"]}}

# Delete test snack
DELETE http://localhost:8000/api/snacks/test-snack
Authorization: Token :token

# Like snack
POST http://localhost:8000/api/snacks/test-snack/favorite
Authorization: Token :token

# Unlike snack
DELETE http://localhost:8000/api/snacks/test-snack/favorite
Authorization: Token :token

# Post comment
POST http://localhost:8000/api/snacks/test-snack/comments
Content-Type: application/json
Authorization: Token :token

{"comment": {"body": "This is amazing!"}}

# Get comments
GET http://localhost:8000/api/snacks/test-snack/comments

# Delete comment. Get id from the "Get comments" and (setq my-restclient-comment-id 3)
DELETE http://localhost:8000/api/snacks/test-snack/comments/:comment-id
Authorization: Token :token

## snacks
# Auth is optional.

# Get snacks as current user
GET http://localhost:8000/api/snacks
Authorization: Token :token

# Get snacks feed. First login as "tester" and follow "stallman".
GET http://localhost:8000/api/snacks/feed
Authorization: Token :token

## Profiles

# Get profile anonymously
GET http://localhost:8000/api/profiles/stallman

# Get profile as current user
GET http://localhost:8000/api/profiles/stallman
Authorization: Token :token

# Follow "stallman". Must be logged in as "tester".
POST http://localhost:8000/api/profiles/stallman/follow
Authorization: Token :token

# Unfollow "stallman". Must be logged in as "tester".
DELETE http://localhost:8000/api/profiles/stallman/follow
Authorization: Token :token

## Tags

# Get tags
GET http://localhost:8000/api/tags
