CREATE TABLE funding (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	author_id UUID NOT NULL REFERENCES users (id),
	slug TEXT UNIQUE NOT NULL,
	title TEXT NOT NULL,
	description TEXT NOT NULL,
	body TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
